version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.23
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - song-service
      - redis
      - postgres
    env_file:
      - .env
    volumes:
      - ./gateway:/app
      - ./utils:/utils

  song-service:
    build:
      context: .
      dockerfile: song-service/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env
    volumes:
      - ./song-service:/app
      - ./utils:/utils

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: "postgres:13"
    env_file:
      - postgres.env
    ports:
      - "5432:5432"